# Generated by Django 4.2.13 on 2024-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('telefone', models.TextField(max_length=11)),
                ('curso', models.TextField(max_length=255)),
            ],
        ),
    ]
